version: "3.9"

services:
  frontend:
    build:
      context: ./product-inventory
      dockerfile: Dockerfile
    ports:
      - "4173:4173"  
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
